correct-command: "&b[服务器娘]&c指令语法错误 正确语法: &e/{command}"
lack-permission: "&b[服务器娘]&c缺少权限 (&e{permission}&c) 来使用指令"
command-sender-error: "&b[服务器娘]&c您必须是一名 &e{type} &c才能这么做"
player-type: "玩家"
admin-type: "管理员"
unknown-type: "未知类型"
reload-message: "&b[服务器娘]&a插件 &eTorosamyCore &a重载成功喵~"

item-attribute-keys:
  display: "display"
  material: "material"
  lore: "lore"
  enchantment: "enchantment"
  item-flag-list: "item-flag-list"
  unbreakable: "unbreakable"
  color: "color"
  amount: "amount"
  trim: "trim"
  horn-instrument: "horn-instrument"
  custom-model-data: "custom-model-data"
  hide-enchantment-glint-override: "hide-enchantment-glint-override"
  glider: "glider"
  equip-namespace: "equip.namespace"
  crossbow-loaded: "crossbow-loaded"
  equip-key: "equip.key"
  equip-slot: "equip.slot"
  equip-fast-wear: "equip.fast-wear"
  consume-food: "consume.food"
  consume-saturation: "consume.saturation"
  consume-ignore-limit: "consume.ignore-limit"
  consume-seconds: "consume.seconds"
  consume-animation: "consume.animation"
  consume-sound: "consume.sound"
  consume-particles: "consume.particles"
  play-animation: "play-animation"
  nbt-int: "nbt-int"
  tool: "tool"
  durability: "durability"
  max-durability: "max-durability"
  nbt-string: "nbt-string"
  fire-resistant: "fire-resistant"
teleport-task-move: "&b[服务器娘]&c传送取消！你在倒计时期间移动了。"
teleport-task-big-title: "&a传送将于 &e%s &a秒开始"
teleport-task-small-title: "&a请勿移动"
teleport-task-unsafe: "&b[服务器娘]&c传送失败! 传送地点不安全"
teleport-cooldown-bypass-permission: "essentials.teleport.cooldown.bypass"

timestamp-format: "yyyy-MM-dd HH:mm:ss"