name: TorosamyCore
main: net.torosamy.torosamyCore.TorosamyCore
version: '${project.version}'
author: '${plugin.yml.author}'
website: '${plugin.yml.website}'
api-version: '${plugin.yml.api}'
depend:
  - PlaceholderAPI